language: python
os: linux
dist: bionic
jobs:
  include:
    - name: "docker-compose"
      if: branch IN (master, dev)
      services: docker
      python: 3.7
      before_install:
        - docker --version
      install: 
        - pip install -U pip
      script: docker-compose build
      after_success:
        -
    - name: "docker-compose-dev"
      if: branch IN (master, dev)
      services: docker
      python: 3.7
      before_install:
        - docker --version
      install: 
        - pip install -U pip
      script: docker-compose -f docker-compose.dev.yml build
      after_success:
        -
    - name: "Python 3.7"
      python: 3.7
      env: TOX_PYTHON_ENV=py37
before_install:
  - ls -la
install:
  - pip install -U pip
  - pip install tox-travis
  - pip install codecov
script:
  - tox -e $TOX_PYTHON_ENV -e lint
after_success:
  - codecov # submit coverage to https://codecov.io/gh/sertansenturk/tomato/
