language: python
jobs:
  include:
    - name: "docker"
      if: branch IN (master, dev)
      services: docker
      python: 3.7
      before_install:
        - docker --version
      install: 
        - pip install -U pip
      script: docker-compose build
      after_success:
        -
    - name: "Python 3.7"
      python: 3.7
      env: TOX_PYTHON_ENV=py37
before_install:
  - ls -la
install:
  - pip install -U pip
  - pip install tox-travis
  - pip install codecov
script:
  - tox -e $TOX_PYTHON_ENV -e lint
after_success:
  - codecov # submit coverage to https://codecov.io/gh/sertansenturk/tomato/
