version: "3.7"
services:
    experiment:
        build:
            context: ./
            dockerfile: docker/experiment/Dockerfile
            target: experiment
        image: sertansenturk/makam_recognition_experiments:latest
        ports:
            - 8888:8888
        volumes:
            - ./:/home/jovyan/work
