version: "3.7"
services:
    jupyter-dev:
        build:
            context: ./
            target: development
        image: sertansenturk/makam_recognition_experiments:dev
        ports:
            - 8888:8888
        volumes:
            - ./:/home/jovyan/work
