version: "3.7"
services:
    experiment-dev:
        build:
            context: ./
            dockerfile: ./docker/experiment/Dockerfile
            target: development
        image: sertansenturk/makam_recognition_experiments:dev
        ports:
            - 8888:8888
        volumes:
            - ./:/home/jovyan/work
    mlflow:
        build:
            context: ./docker/mlflow/
            dockerfile: ./Dockerfile
        image: sertansenturk/mlflow:latest
        expose:
            - 5000
        ports:
            - 5000:5000
        volumes:
            - ./mlflow-store:/server/mlflow-store
            - ./mlflow-artifacts:/server/mlflow-artifacts
    